- name: "----creating the repo for kubernetes----"
  copy:
      src: "kubernetes.repo"
      dest: "/etc/yum.repos.d/"

- name: "----installing docker, kubeadm, iproute-tc----"
  package:
       name:
       - docker
       - kubeadm
       - iproute-tc
       state: present

- name: "----changing cgroup driver from cgroupfs to systemd----"
  copy:
      src: "daemon.json"
      dest: "/etc/docker/"

- name: "----starting the docker service----"
  service:
       name: "{{ item }}"
       state: started
       enabled: yes
  loop:
  - "docker"
  - "kubelet"

- name: "----pulling kubernetes related images with kubeconfig----"
  command: "kubeadm config images pull"

- name: "----Updating IP tables on Master Node----"
  copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

- name: "----Reloading sysctl on Master Node----"
  command: sysctl --system

- name: "----closing swap----"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "----Now its time to initialize the Master----"
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=mem"
  
- name: "----creating master as a user also----"
  shell: "{{ item }}"
  loop:
       - mkdir -p $HOME/.kube
       - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
       - sudo chown $(id -u):$(id -g) $HOME/.kube/config
- name: "----creating token for Worker node----"
  shell: "kubeadm token create --print-join-command"
  register: token

- debug:
     var: token.stdout

- name: "----creating flannel pods for connectivity btw nodes---- "
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
   
- debug:
        msg: "****MASTER HAS SET UP SUCCESSFULLY****"
