
- name: "----creating the repo for kubernetes----"
  copy:
      src: "kubernetes.repo"
      dest: "/etc/yum.repos.d/"

- name: "----installing docker, kubeadm, iproute-tc----"
  package:
       name:
       - docker
       - kubeadm
       - iproute-tc
       state: present

- name: "----changing cgroup driver from cgroupfs to systemd----"
  copy:
      src: "daemon.json"
      dest: "/etc/docker/"

- name: "----starting the docker service-----"
  service:
       name: "{{ item }}"
       state: started
       enabled: yes
  loop:
        - "docker"
        - "kubelet"
- name: " ----pulling kubernetes related images with kubeconfig---- "
  command: "kubeadm config images pull"

- name: "----Updating IP tables on Slave Node----"
  copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

- name: "----Reloading sysctl on Slave Node----"
  command: sysctl --system

- name: "----closing swap----"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "----joining worker nodes with master----"
  command: "{{ hostvars[groups['masternode'][0]]['token']['stdout'] }}"

- debug: 
      msg: "WORKER NODES SUCCESSFULLY JOIN"
