apiVersion: apps/v1
kind: Deployment
metadata:
        name: "sql-deploy"
spec:
        replicas: 2
        selector:
                matchLabels:
                        Name: "SQL"
        template:
                metadata: 
                    name: "mysql-pod"
                    labels:
                            Name: "SQL"
                spec:
                        containers:
                        - name: "sql-cont"
                          image: "mysql:5.7"
                          env:
                          - name: "MYSQL_ROOT_PASSWORD"
                            value: "pranay"
                          
                          - name: "MYSQL_DATABASE"
                            value: "mydb"

                          - name: "MYSQL_USER"
                            value: "wordpress"
                            
                          - name: "MYSQL_PASSWORD"
                            value: "pranay"  




