apiVersion: v1
kind: Service
metadata:
        name: "sql-load-balancer"

spec:
        type: "ClusterIP"
        ports:
                - targetPort: 3306
                  port: 8080
        selector:
             Name: "SQL"


