apiVersion: v1
kind: Service
metadata: 
   name: "wordpress-load-balancer"

spec: 
  selector:
          Name: "wordpress"

  type: "NodePort"

  ports:
    - targetPort: 80
      port: 8080
      nodePort: 31000    
          

